server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: 5000
myCustomVariableTree:
  welcomeMsg: Hello from prod
---
spring:
  config:
    activate:
      on-profile: test
server:
  port: 4000
myCustomVariableTree:
  welcomeMsg: Hello from test
